sudo: required
services:
  docker

  before_install:
    - docker build -t snaky912/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run snaky912/react-test npm test -- --coverage

after_success:
  - docker build -t snaky912/multi-client ./client
  - docker build -t snaky912/multi-nginx ./nginx
  - docker build -t snaky912/multi-server ./server
  - docker build -t snaky912/multi-worker ./worker
  # Log into the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push snaky912/multi-client
  - docker push snaky912/multi-nginx
  - docker push snaky912/multi-server
  - docker push snaky912/multi-worker